#!/bin/sh
#
# File:    lologEstimation2textable.sh
# Author:  Alex Stivala
# Created: September 2021
#
# Read last estimation result from a latent order logistic (lolog)
# as produced by the summary() method on a lolog model in the
# lolog R package (https://cran.r-project.org/web/packages/lolog/index.html)
# and convert to LaTeX table.
#
# Usage: lologEstimation2textable.sh   estimation_output_file.txt
#
# E.g.:
#   lologEstimation2textable.sh.sh  yeast_transcription_lolog_model1.txt
#
# Output is to stdout
#
# Uses various GNU utils options on echo, etc.
#
# Parses output that looks like this:
#                  observed_statistics      theta         se pvalue
# edges                      1079.0000 -4.1066677 0.07767241      0
# twoPath                     386.0000 -0.7062469 0.06555177      0
# triangles                    74.0000  2.6632668 0.16593393      0
# in-gwdegree.0.2             644.1676  1.0385543 0.10476393      0
# out-gwdegree.0.2            152.3870 -3.9870033 0.11783041      0
#

if [ $# -ne 1 ]; then
    echo "usage: $0 estimation_file.txt" >&2
    exit 1
fi

estimationresults=$1

tmpfile=`mktemp`

echo "% Generated by: $0 $*"
echo "% At: " `date`
echo "% On: " `uname -a`


#format into LaTeX table with 4 digits on floating point numbers

echo '\begin{tabular}{lrrr}'
echo '\hline'  
echo 'Effect & Estimate & Std. error & p-value\\'
echo '\hline'

#tail -n+2  ${estimationresults} | awk '{printf("%s & $%.4f$ & $%.4f$ & $%g$ \\\\\n",$1,$3,$4,$5)}'

tail -n+2  ${estimationresults} | awk '{printf("%s & $%.4f$ & $%.4f$ & $%s$ \\\\\n",$1,$3,$4, (sprintf("%g", $5) < 0.001 ? "< 0.001" : sprintf("%g", $5)))}'

echo '\hline'  
echo '\end{tabular}'


rm $tmpfile
