#!/usr/bin/Rscript
##
## File:    plotMotifCountsBoxPlots.R
## Author:  Alex Stivala
## Created: September 2021
##
## Read tables generated by motifsNetMODEobsSim.R
## and make boxplots for simulated networks with point for
## observed network on same plot for comparison.
##
## Usage: Rscript plotMotifCountsBoxPlots.R motif_counts_table.txt
##
##    motif_counts_table.txt is output of motifsNetMODEobsSim.R
##   
##  output files are built from basename of moutif_counts_table.txt file as:
##        motif_counts_table.eps
##
##  WARNING: output files are overwritten
##
## Example:
##      Rscript plotEsimtNetDirectedSimFit.R ecoli_tetrads.txt
##
##
##
## Input file format example:
##
## motif_size motif_id network_id network_type motif_count
## 4 204 observed observed 209
## 4 204 1 simulated 10
## 4 204 2 simulated 8
##  ...


library(ggplot2)
library(doBy)

##
## label function for ggplot2 labeller
##
label_function <- function(variable, value) {
    sapply(value, FUN = function(xval) 
        if (xval == '204') {
          "Bi-fan"
        } else if  (xval == '2182') {
          "Bi-parallel"
        }  else {
          levels(xval)[xval]
        }
    )
}

###
### Main
###
args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 1) {
  cat("Usage: Rscript plotMotifCountsBoxPlots.R motif_counts_table.txt\n")
  quit(save="no")
}
tablefilename <- args[1]

tablename <- sub("(.+)[.].+", "\\1", basename(tablefilename))

obscolour <- 'red' # colour to plot observed graph points/lines
## simulated graph statistics will be boxplot on same plot in default colour

ptheme <-  theme(legend.position = 'none')

dat <- read.table(tablefilename, header=TRUE, stringsAsFactors=FALSE)

dat$motif_id <- factor(dat$motif_id)
dat$motif_name <- factor(label_function(NA, dat$motif_id))
datsim <- dat[which(dat$network_type == "simulated"),]
obs_dat <- dat[which(dat$network_type == "observed"),]


p <- ggplot(datsim, aes(x = motif_name, y = motif_count))
p <- p + geom_boxplot()
p <- p + ptheme + xlab("Motif") + ylab('Count')
p <- p + theme(axis.text = element_text(size = 20))
p <- p + theme(axis.title = element_text(size = 20))
p <- p + theme(plot.title = element_text(size = 20))
p <- p + geom_point(data=obs_dat, aes(x = motif_name, y = motif_count, group=1), 
                                      colour = obscolour,shape=23,size=4)

outputepsfilename <- paste(tablename, 'eps', sep='.')
cat('Writing to ', outputepsfilename, '\n')
postscript(outputepsfilename, onefile=FALSE, horizontal=FALSE, paper="special", width=9, height=6)
print(p)
dev.off()
